name: CI

on:
  push:
    branches:
      - master
      - blas
  pull_request:
    branches:
      - master
      - blas
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-linux:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Lean Action
        uses: leanprover/lean-action@v1
      - name: Build BLAS
        run: lake build leanblas
      - name: Build project
        run: lake build
      - name: Run Tests
        run: lake test
      - name: Run Examples
        run: make examples

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Lean Action
        uses: leanprover/lean-action@v1
      - name: Build BLAS
        run: lake build leanblas
      - name: Build project
        run: lake build
      - name: Run Tests
        run: lake test
      - name: Run Examples
        run: make examples
